name: Build

on:
  release:
    types: [published]

jobs:
  build-skycore:
    name: Build Skycore
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.1.0
      
      - name: Set up skopeo
        uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest 

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Run SKYCORE build script
        run: |
          python build.py

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
